language: go

go:
  - 1.9.x # See README.md for current minimum version.
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  
script:
  - make check_license unused test-short
  - if [[ ! $TRAVIS_GO_VERSION =~ ^1\.(9|10|11)\. ]]; then make lint; fi
  # Style is only checked against the latest supported Go version.
  - if [[ $TRAVIS_GO_VERSION =~ ^1\.(14)\. ]]; then make style; fi
