language: go

before_script:
 - go get -v github.com/matttproud/golang_instrumentation

script:
 - go build -a -v github.com/matttproud/golang_instrumentation/...
 - go test -v github.com/matttproud/golang_instrumentation/...
